name: CI

on:
  push:
    branches:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Check
        run: ./gradlew check --stacktrace

      - name: Publish reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports
