name: CI

on:
  push:
    branches:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Check
        run: ./gradlew check --stacktrace

      - name: Publish reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports
