name: Publish

on: push

jobs:
  Publish:
    runs-on: ubuntu-22.04

    env:
      GITHUB_READPACKAGES_USER: ${{ secrets.GH_READPACKAGES_USER }}
      GITHUB_READPACKAGES_TOKEN: ${{ secrets.GH_READPACKAGES_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run linters and unit tests
        run: ./gradlew ktlintCheck test --stacktrace

      - name: Publish test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests
        if: ${{ failure() }}

      - name: Publish JAR
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
